export const articles = [
  {
    id: 'A01',
    slug: 'car-wont-start-causes',
    title: "Why Your Car Won't Start — 12 Common Causes & Fixes",
    description: "Car won't start? Learn the 12 most common causes from dead batteries to fuel pump failure, with diagnosis steps and repair costs in Malaysia (RM).",
    category: 'car-problems',
    tags: ['car won\'t start', 'kereta tak boleh start', 'car cranks but won\'t start', 'no start diagnosis', 'car troubleshooting'],
    primaryKeyword: "car won't start",
    difficulty: 'beginner',
    readingTime: '8 min read',
    publishedAt: '2026-04-15',
    priority: 'P1',
    cta: 'health-scan',
  },
  {
    id: 'A02',
    slug: 'engine-overheating-causes',
    title: 'Engine Overheating — Causes, Symptoms & What to Do',
    description: 'Engine overheating in Malaysian traffic? Learn the causes, warning signs, and what to do immediately. Includes repair costs in RM and prevention tips.',
    category: 'car-problems',
    tags: ['engine overheating', 'kereta overheat', 'coolant temperature high', 'car temperature warning', 'radiator problem'],
    primaryKeyword: 'engine overheating',
    difficulty: 'beginner',
    readingTime: '7 min read',
    publishedAt: '2026-04-15',
    priority: 'P1',
    cta: 'health-scan',
  },
  {
    id: 'A03',
    slug: 'check-engine-light-meaning',
    title: "Check Engine Light On? Here's What It Means & What to Do",
    description: "Check engine light on your dashboard? Learn what triggers it, how serious it is, and how to read the fault code yourself using BYKI. Malaysia guide.",
    category: 'car-problems',
    tags: ['check engine light', 'engine warning light', 'CEL on', 'lampu engine menyala', 'MIL light'],
    primaryKeyword: 'check engine light',
    difficulty: 'beginner',
    readingTime: '7 min read',
    publishedAt: '2026-04-15',
    priority: 'P1',
    cta: 'fault-codes',
  },
  {
    id: 'A04',
    slug: 'car-jerking-when-accelerating',
    title: 'Car Jerking When Accelerating — Causes & How to Fix',
    description: 'Car jerking or hesitating when you accelerate? Here are the 10 most common causes, how to diagnose each one, and estimated repair costs in Malaysia.',
    category: 'car-problems',
    tags: ['car jerking', 'kereta tersentak', 'car hesitation', 'car stuttering', 'acceleration problem'],
    primaryKeyword: 'car jerking when accelerating',
    difficulty: 'beginner',
    readingTime: '8 min read',
    publishedAt: '2026-04-15',
    priority: 'P1',
    cta: 'health-scan',
  },
  {
    id: 'A05',
    slug: 'engine-misfiring-symptoms',
    title: 'Engine Misfire — Symptoms, Causes & Diagnosis',
    description: 'Engine misfiring? Learn the symptoms (shaking, loss of power, rough idle), 8 common causes, and how to diagnose which cylinder is misfiring.',
    category: 'car-problems',
    tags: ['engine misfire', 'car misfiring', 'engine shaking', 'misfire code', 'P0300 P0301'],
    primaryKeyword: 'engine misfire',
    difficulty: 'intermediate',
    readingTime: '9 min read',
    publishedAt: '2026-04-15',
    priority: 'P1',
    cta: 'fault-codes',
  },
  {
    id: 'A06',
    slug: 'car-idling-rough',
    title: 'Why Is My Car Idling Rough? Causes & Solutions',
    description: 'Car shaking or vibrating at idle? Rough idle has many causes — from dirty throttle bodies to vacuum leaks. Full diagnosis guide with RM repair costs.',
    category: 'car-problems',
    tags: ['rough idle', 'kereta idle tak stabil', 'car shaking at idle', 'engine vibrating', 'unstable RPM'],
    primaryKeyword: 'rough idle',
    difficulty: 'beginner',
    readingTime: '7 min read',
    publishedAt: '2026-04-15',
    priority: 'P1',
    cta: 'health-scan',
  },
  {
    id: 'A07',
    slug: 'car-losing-power-uphill',
    title: "Car Losing Power When Going Uphill — What's Wrong?",
    description: "Car struggling or losing power on hills? Learn why your engine can't deliver enough power under load, common causes, and what to check first.",
    category: 'car-problems',
    tags: ['car losing power', 'kereta tak laju', 'loss of acceleration', 'car sluggish uphill', 'engine power loss'],
    primaryKeyword: 'car losing power',
    difficulty: 'beginner',
    readingTime: '7 min read',
    publishedAt: '2026-04-15',
    priority: 'P1',
    cta: 'health-scan',
  },
  {
    id: 'A08',
    slug: 'car-stalling-causes',
    title: 'Why Does My Car Keep Stalling? Common Causes',
    description: 'Car engine stalling or dying while driving? Learn the 9 most common causes of engine stalling, from fuel delivery issues to sensor failures. Malaysia guide.',
    category: 'car-problems',
    tags: ['car stalling', 'kereta mati sendiri', 'engine dies while driving', 'car shuts off', 'stall at traffic light'],
    primaryKeyword: 'car stalling',
    difficulty: 'beginner',
    readingTime: '7 min read',
    publishedAt: '2026-04-15',
    priority: 'P1',
    cta: 'health-scan',
  },
  {
    id: 'A09',
    slug: 'engine-knocking-sound',
    title: 'Engine Knocking Sound — What It Means & Is It Serious?',
    description: 'Hearing a knocking, pinging, or ticking from your engine? Learn what different engine sounds mean, what causes them, and when you need urgent repair.',
    category: 'car-problems',
    tags: ['engine knocking', 'ketuk engine', 'engine ticking', 'pinging sound', 'engine noise'],
    primaryKeyword: 'engine knocking',
    difficulty: 'beginner',
    readingTime: '7 min read',
    publishedAt: '2026-04-15',
    priority: 'P1',
    cta: 'health-scan',
  },
  {
    id: 'A10',
    slug: 'car-wont-accelerate',
    title: "Car Won't Accelerate Properly — Causes & Diagnosis",
    description: "Car not picking up speed or feels sluggish? Learn the 10 most common reasons your car won't accelerate and how to diagnose the problem.",
    category: 'car-problems',
    tags: ['car won\'t accelerate', 'car not picking up speed', 'slow acceleration', 'kereta tak laju', 'throttle response poor'],
    primaryKeyword: "car won't accelerate",
    difficulty: 'beginner',
    readingTime: '8 min read',
    publishedAt: '2026-04-15',
    priority: 'P1',
    cta: 'health-scan',
  },
  {
    id: 'B01',
    slug: 'p0171-system-too-lean',
    title: 'P0171 System Too Lean — Causes, Symptoms & Fix Cost',
    description: 'P0171 means your engine is running too lean (too much air, not enough fuel). Learn the causes, symptoms, and repair costs in Malaysia (RM).',
    category: 'fault-codes',
    tags: ['P0171', 'system too lean', 'lean engine code', 'fuel trim high', 'vacuum leak code'],
    primaryKeyword: 'P0171',
    difficulty: 'intermediate',
    readingTime: '9 min read',
    publishedAt: '2026-04-29',
    priority: 'P1',
    cta: 'fault-codes',
  },
  {
    id: 'B02',
    slug: 'p0172-system-too-rich',
    title: 'P0172 System Too Rich — What It Means & How to Fix',
    description: 'P0172 means your engine runs too rich (excess fuel). Learn common causes like leaking injectors and faulty O2 sensors, with RM repair costs.',
    category: 'fault-codes',
    tags: ['P0172', 'system too rich', 'rich fuel mixture', 'black smoke code', 'fuel injector leak'],
    primaryKeyword: 'P0172',
    difficulty: 'intermediate',
    readingTime: '8 min read',
    publishedAt: '2026-04-29',
    priority: 'P1',
    cta: 'fault-codes',
  },
  {
    id: 'B03',
    slug: 'p0300-random-misfire',
    title: 'P0300 Random Misfire Detected — Complete Diagnosis Guide',
    description: 'P0300 means multiple cylinders are misfiring randomly. Learn why, what causes it, and how to fix it. Malaysia diagnosis guide with RM costs.',
    category: 'fault-codes',
    tags: ['P0300', 'random misfire', 'multiple cylinder misfire', 'engine shaking code', 'misfire detected'],
    primaryKeyword: 'P0300',
    difficulty: 'intermediate',
    readingTime: '9 min read',
    publishedAt: '2026-04-29',
    priority: 'P1',
    cta: 'fault-codes',
  },
  {
    id: 'B04',
    slug: 'p0301-cylinder-1-misfire',
    title: 'P0301 Cylinder 1 Misfire — Spark Plug, Coil or Injector?',
    description: 'P0301 means cylinder 1 is misfiring. Learn how to identify whether it\'s the spark plug, ignition coil, or fuel injector causing it.',
    category: 'fault-codes',
    tags: ['P0301', 'cylinder 1 misfire', 'misfire code', 'spark plug misfire', 'ignition coil failure'],
    primaryKeyword: 'P0301',
    difficulty: 'intermediate',
    readingTime: '8 min read',
    publishedAt: '2026-04-29',
    priority: 'P1',
    cta: 'fault-codes',
  },
  {
    id: 'B05',
    slug: 'p0302-cylinder-2-misfire',
    title: 'P0302 Cylinder 2 Misfire — Diagnosis & Repair Cost',
    description: 'P0302 indicates cylinder 2 is misfiring. Full diagnosis walkthrough with causes, live data analysis tips, and Malaysian repair cost estimates.',
    category: 'fault-codes',
    tags: ['P0302', 'cylinder 2 misfire', 'misfire diagnosis', 'engine vibration code', 'coil swap test'],
    primaryKeyword: 'P0302',
    difficulty: 'intermediate',
    readingTime: '8 min read',
    publishedAt: '2026-04-29',
    priority: 'P1',
    cta: 'fault-codes',
  },
  {
    id: 'B06',
    slug: 'p0303-cylinder-3-misfire',
    title: 'P0303 Cylinder 3 Misfire — Common Causes in Malaysian Cars',
    description: 'P0303 means cylinder 3 is misfiring. Particularly common in 4-cylinder Perodua and Proton engines. Full diagnosis and RM cost guide.',
    category: 'fault-codes',
    tags: ['P0303', 'cylinder 3 misfire', 'Perodua misfire', 'Proton misfire', 'misfire fix'],
    primaryKeyword: 'P0303',
    difficulty: 'intermediate',
    readingTime: '7 min read',
    publishedAt: '2026-04-29',
    priority: 'P1',
    cta: 'fault-codes',
  },
  {
    id: 'B07',
    slug: 'p0304-cylinder-4-misfire',
    title: 'P0304 Cylinder 4 Misfire — Diagnosis Guide',
    description: 'P0304 flags a misfire in cylinder 4. Learn the likely causes, step-by-step diagnosis procedure, and when to replace vs repair.',
    category: 'fault-codes',
    tags: ['P0304', 'cylinder 4 misfire', 'last cylinder misfire', 'ignition diagnosis', 'misfire repair'],
    primaryKeyword: 'P0304',
    difficulty: 'intermediate',
    readingTime: '7 min read',
    publishedAt: '2026-04-29',
    priority: 'P1',
    cta: 'fault-codes',
  },
  {
    id: 'B08',
    slug: 'p0420-catalyst-efficiency',
    title: 'P0420 Catalyst Efficiency Below Threshold — Fix or Replace?',
    description: 'P0420 means your catalytic converter isn\'t working efficiently. Learn whether you need to replace it or if a cheaper fix exists. Malaysia guide.',
    category: 'fault-codes',
    tags: ['P0420', 'catalytic converter code', 'catalyst efficiency', 'cat con replacement', 'O2 sensor downstream'],
    primaryKeyword: 'P0420',
    difficulty: 'intermediate',
    readingTime: '9 min read',
    publishedAt: '2026-04-29',
    priority: 'P1',
    cta: 'fault-codes',
  },
  {
    id: 'B09',
    slug: 'p0430-catalyst-bank-2',
    title: 'P0430 Catalyst System Efficiency Below Threshold (Bank 2)',
    description: 'P0430 is the Bank 2 version of P0420 — your second catalytic converter is underperforming. Causes, diagnosis, and repair costs in RM.',
    category: 'fault-codes',
    tags: ['P0430', 'catalyst bank 2', 'V-engine catalyst', 'P0430 vs P0420', 'exhaust system code'],
    primaryKeyword: 'P0430',
    difficulty: 'intermediate',
    readingTime: '7 min read',
    publishedAt: '2026-04-29',
    priority: 'P1',
    cta: 'fault-codes',
  },
  {
    id: 'B10',
    slug: 'p0128-thermostat-below-temp',
    title: 'P0128 Coolant Thermostat Below Temperature — Fix Guide',
    description: 'P0128 means the engine isn\'t reaching operating temperature fast enough — usually a stuck-open thermostat. Simple fix guide with RM costs.',
    category: 'fault-codes',
    tags: ['P0128', 'thermostat code', 'coolant temperature low', 'engine cold too long', 'thermostat stuck open'],
    primaryKeyword: 'P0128',
    difficulty: 'beginner',
    readingTime: '7 min read',
    publishedAt: '2026-04-29',
    priority: 'P1',
    cta: 'fault-codes',
  },
  {
    id: 'D01',
    slug: '0w20-vs-5w30-difference',
    title: '0W-20 vs 5W-30 — Which Oil Is Right for Your Car?',
    description: '0W-20 vs 5W-30 explained: which viscosity your car needs, why it matters, and what happens if you use the wrong one. Malaysia climate guide.',
    category: 'oil-guide',
    tags: ['0W-20 vs 5W-30', 'oil viscosity comparison', 'which oil for my car', 'engine oil Malaysia', 'viscosity grade'],
    primaryKeyword: '0W-20 vs 5W-30',
    difficulty: 'beginner',
    readingTime: '8 min read',
    publishedAt: '2026-05-13',
    priority: 'P1',
    cta: 'oil-finder',
  },
  {
    id: 'D02',
    slug: '5w30-vs-5w40-explained',
    title: '5W-30 vs 5W-40 — Choosing the Right Viscosity',
    description: '5W-30 or 5W-40? Learn the real difference, which is better for Malaysian weather, and how to pick the right one for your engine.',
    category: 'oil-guide',
    tags: ['5W-30 vs 5W-40', 'oil viscosity', 'thicker oil better', 'engine oil grade', 'viscosity difference'],
    primaryKeyword: '5W-30 vs 5W-40',
    difficulty: 'beginner',
    readingTime: '7 min read',
    publishedAt: '2026-05-13',
    priority: 'P1',
    cta: 'oil-finder',
  },
  {
    id: 'D03',
    slug: 'synthetic-vs-mineral-oil',
    title: 'Synthetic vs Mineral Oil — Is Synthetic Worth the Price?',
    description: 'Synthetic oil costs more — but is it worth it? We compare performance, protection, change intervals, and value for Malaysian car owners.',
    category: 'oil-guide',
    tags: ['synthetic vs mineral oil', 'fully synthetic oil', 'mineral oil car', 'minyak hitam sintetik', 'oil type comparison'],
    primaryKeyword: 'synthetic vs mineral oil',
    difficulty: 'beginner',
    readingTime: '8 min read',
    publishedAt: '2026-05-13',
    priority: 'P1',
    cta: 'oil-finder',
  },
  {
    id: 'D04',
    slug: 'semi-synthetic-vs-full-synthetic',
    title: "Semi-Synthetic vs Full Synthetic — What's the Real Difference?",
    description: "Semi-synthetic is cheaper, full synthetic lasts longer — but what's actually different? Clear comparison with RM pricing for Malaysian car owners.",
    category: 'oil-guide',
    tags: ['semi synthetic vs full synthetic', 'semi sintetik', 'oil comparison', 'engine oil types', 'which oil type'],
    primaryKeyword: 'semi synthetic vs full synthetic',
    difficulty: 'beginner',
    readingTime: '7 min read',
    publishedAt: '2026-05-13',
    priority: 'P1',
    cta: 'oil-finder',
  },
  {
    id: 'D05',
    slug: 'what-does-0w20-mean',
    title: 'What Does 0W-20 Mean? Oil Viscosity Explained Simply',
    description: "What do the numbers on your engine oil bottle mean? Learn how to read viscosity grades like 0W-20, 5W-30, 5W-40 — explained for beginners.",
    category: 'oil-guide',
    tags: ['what does 0W-20 mean', 'oil viscosity explained', 'SAE viscosity grade', 'engine oil numbers', 'W meaning oil'],
    primaryKeyword: 'what does 0W-20 mean',
    difficulty: 'beginner',
    readingTime: '6 min read',
    publishedAt: '2026-05-13',
    priority: 'P1',
    cta: 'oil-finder',
  },
  {
    id: 'C01',
    slug: 'perodua-myvi-common-problems',
    title: 'Perodua Myvi Common Problems & How to Diagnose Them',
    description: "Complete guide to Perodua Myvi common problems across all generations. Learn the issues, warning signs, and how to diagnose with BYKI.",
    category: 'vehicle-guide',
    tags: ['Perodua Myvi problems', 'Myvi common issues', 'Myvi engine problem', 'Myvi check engine light', 'masalah Myvi'],
    primaryKeyword: 'Perodua Myvi problems',
    difficulty: 'beginner',
    readingTime: '10 min read',
    publishedAt: '2026-05-13',
    priority: 'P1',
    cta: 'health-scan',
  },
  {
    id: 'C07',
    slug: 'best-engine-oil-perodua',
    title: 'Best Engine Oil for All Perodua Models (2024–2026 Guide)',
    description: "Find the right engine oil for every Perodua model — Myvi, Axia, Bezza, Ativa, Alza, Aruz. Includes viscosity, type, and RM price comparison.",
    category: 'vehicle-guide',
    tags: ['best oil for Perodua', 'Perodua engine oil', 'Myvi oil recommendation', 'Axia oil type', 'minyak hitam Perodua'],
    primaryKeyword: 'best oil for Perodua',
    difficulty: 'beginner',
    readingTime: '9 min read',
    publishedAt: '2026-05-13',
    priority: 'P1',
    cta: 'oil-finder',
  },
  {
    id: 'C09',
    slug: 'proton-x50-common-problems',
    title: 'Proton X50 Common Problems — 1.5T Turbo Issues & Tips',
    description: "Proton X50 owner? Learn the common problems with the 1.5T turbo engine, DCT transmission, and electronics — plus how to diagnose early with BYKI.",
    category: 'vehicle-guide',
    tags: ['Proton X50 problems', 'X50 turbo issues', 'X50 DCT problem', 'Proton X50 maintenance', 'masalah X50'],
    primaryKeyword: 'Proton X50 problems',
    difficulty: 'beginner',
    readingTime: '10 min read',
    publishedAt: '2026-05-13',
    priority: 'P1',
    cta: 'health-scan',
  },
  {
    id: 'C16',
    slug: 'best-engine-oil-proton',
    title: 'Best Engine Oil for All Proton Models — Complete Guide',
    description: "Find the right engine oil for every Proton model — Saga, Persona, X50, X70, S70, Iriz, X90. Viscosity, type, and price guide.",
    category: 'vehicle-guide',
    tags: ['best oil for Proton', 'Proton engine oil', 'X50 oil recommendation', 'Saga oil type', 'minyak hitam Proton'],
    primaryKeyword: 'best oil for Proton',
    difficulty: 'beginner',
    readingTime: '9 min read',
    publishedAt: '2026-05-13',
    priority: 'P1',
    cta: 'oil-finder',
  },
  {
    id: 'C17',
    slug: 'toyota-vios-common-problems',
    title: 'Toyota Vios Common Problems — Generation Guide',
    description: "Toyota Vios common problems across NCP93, NCP150, and latest generation. Engine, CVT, electrical issues and how to diagnose them.",
    category: 'vehicle-guide',
    tags: ['Toyota Vios problems', 'Vios common issues', 'Vios engine problem', 'Vios CVT issue', 'masalah Vios'],
    primaryKeyword: 'Toyota Vios problems',
    difficulty: 'beginner',
    readingTime: '10 min read',
    publishedAt: '2026-05-13',
    priority: 'P1',
    cta: 'health-scan',
  },
  {
    id: 'B56',
    slug: 'what-is-dtc-code',
    title: "What Is a DTC Code? Complete Beginner's Guide",
    description: "DTC stands for Diagnostic Trouble Code — a standardised fault code your car's computer stores when something goes wrong. Complete beginner's guide.",
    category: 'fault-codes',
    tags: ['what is DTC', 'diagnostic trouble code', 'DTC meaning', 'car fault code', 'OBD2 code'],
    primaryKeyword: 'what is a DTC code',
    difficulty: 'beginner',
    readingTime: '7 min read',
    publishedAt: '2026-05-27',
    priority: 'P1',
    cta: 'fault-codes',
  },
  {
    id: 'B57',
    slug: 'stored-vs-pending-vs-permanent-dtc',
    title: "Stored vs Pending vs Permanent DTC — What's the Difference?",
    description: "Not all fault codes are the same. Learn the difference between stored, pending, and permanent DTCs — and what each means for your car.",
    category: 'fault-codes',
    tags: ['pending DTC', 'stored code vs pending', 'permanent DTC', 'DTC types', 'fault code status'],
    primaryKeyword: 'pending DTC',
    difficulty: 'beginner',
    readingTime: '7 min read',
    publishedAt: '2026-05-27',
    priority: 'P1',
    cta: 'fault-codes',
  },
  {
    id: 'B58',
    slug: 'how-to-read-fault-codes',
    title: 'How to Read Car Fault Codes — Free With Your Phone',
    description: "You don't need expensive tools to read fault codes. Learn how to scan your car using your phone and a Bluetooth OBD-II adapter. Step-by-step guide.",
    category: 'fault-codes',
    tags: ['how to read fault codes', 'read DTC with phone', 'OBD2 code reader', 'scan car codes', 'free car diagnostic'],
    primaryKeyword: 'how to read fault codes',
    difficulty: 'beginner',
    readingTime: '8 min read',
    publishedAt: '2026-05-27',
    priority: 'P1',
    cta: 'fault-codes',
  },
  {
    id: 'B59',
    slug: 'should-i-clear-fault-codes',
    title: 'Should You Clear Fault Codes? When It Helps & When It Hurts',
    description: "Tempted to clear that check engine light? Learn when clearing fault codes is helpful, when it's risky, and what information you lose.",
    category: 'fault-codes',
    tags: ['clear fault codes', 'clear DTC', 'reset check engine light', 'clear MIL', 'erase codes'],
    primaryKeyword: 'clear fault codes',
    difficulty: 'beginner',
    readingTime: '7 min read',
    publishedAt: '2026-05-27',
    priority: 'P1',
    cta: 'fault-codes',
  },
  {
    id: 'B60',
    slug: 'most-common-check-engine-codes-malaysia',
    title: '20 Most Common Check Engine Light Codes in Malaysia',
    description: "The 20 fault codes Malaysian mechanics see most often — from P0171 to P0420. What each code means, how serious it is, and estimated RM repair costs.",
    category: 'fault-codes',
    tags: ['common check engine codes', 'most common DTC Malaysia', 'frequent fault codes', 'P0171 P0300 P0420', 'check engine light codes'],
    primaryKeyword: 'common check engine codes',
    difficulty: 'beginner',
    readingTime: '12 min read',
    publishedAt: '2026-05-27',
    priority: 'P1',
    cta: 'fault-codes',
  },
  {
    id: 'D12',
    slug: 'engine-oil-change-cost-malaysia',
    title: 'Engine Oil Change Cost in Malaysia (2026 Price Guide)',
    description: "How much does an oil change cost in Malaysia? Complete 2026 price breakdown by oil type, car brand, and workshop type. RM pricing guide.",
    category: 'oil-guide',
    tags: ['oil change cost Malaysia', 'tukar minyak hitam harga', 'service kereta harga', 'engine oil price', 'car service cost'],
    primaryKeyword: 'oil change cost Malaysia',
    difficulty: 'beginner',
    readingTime: '8 min read',
    publishedAt: '2026-05-27',
    priority: 'P1',
    cta: 'oil-finder',
  },
  {
    id: 'D13',
    slug: 'how-often-change-engine-oil-malaysia',
    title: 'How Often Should You Change Engine Oil in Malaysia?',
    description: "5,000 km? 10,000 km? The right oil change interval depends on your oil type, car, and driving conditions. Malaysia-specific guide.",
    category: 'oil-guide',
    tags: ['how often change oil', 'oil change interval Malaysia', 'tukar minyak hitam bila', 'engine oil change frequency', 'oil change schedule'],
    primaryKeyword: 'how often change oil Malaysia',
    difficulty: 'beginner',
    readingTime: '7 min read',
    publishedAt: '2026-05-27',
    priority: 'P1',
    cta: 'oil-finder',
  },
  {
    id: 'D16',
    slug: 'petronas-syntium-7000-review',
    title: 'Petronas Syntium 7000 0W-20 Review — Worth the Premium?',
    description: "Is Petronas Syntium 7000 worth RM 200+? In-depth review of Malaysia's top 0W-20 oil — performance, protection, value, and who should use it.",
    category: 'oil-guide',
    tags: ['Petronas Syntium 7000 review', 'Syntium 7000 0W-20', 'best 0W-20 Malaysia', 'Petronas oil review', 'Syntium 7000 worth it'],
    primaryKeyword: 'Petronas Syntium 7000 review',
    difficulty: 'beginner',
    readingTime: '8 min read',
    publishedAt: '2026-05-27',
    priority: 'P1',
    cta: 'oil-finder',
  },
  {
    id: 'D22',
    slug: 'best-0w20-oil-malaysia',
    title: '5 Best 0W-20 Engine Oils in Malaysia (2026)',
    description: "Looking for the best 0W-20 oil in Malaysia? We compare 5 top products — Petronas, Shell, Castrol, Liqui Moly, and Mobil — on performance and price.",
    category: 'oil-guide',
    tags: ['best 0W-20 oil Malaysia', '0W-20 oil review', 'top engine oil Malaysia', '0W-20 comparison', 'Perodua oil recommendation'],
    primaryKeyword: 'best 0W-20 oil Malaysia',
    difficulty: 'beginner',
    readingTime: '9 min read',
    publishedAt: '2026-05-27',
    priority: 'P1',
    cta: 'oil-finder',
  },
  {
    id: 'D24',
    slug: 'best-engine-oil-brands-malaysia',
    title: 'Best Engine Oil Brands in Malaysia — Complete Ranking',
    description: "Petronas, Shell, Castrol, Liqui Moly, Mobil — which engine oil brand is best in Malaysia? We rank them on quality, value, and availability.",
    category: 'oil-guide',
    tags: ['best engine oil Malaysia', 'engine oil brand ranking', 'Petronas vs Shell vs Castrol', 'top oil brand Malaysia', 'minyak hitam terbaik'],
    primaryKeyword: 'best engine oil Malaysia',
    difficulty: 'beginner',
    readingTime: '10 min read',
    publishedAt: '2026-05-27',
    priority: 'P1',
    cta: 'oil-finder',
  },
]

export const CATEGORY_LABELS = {
  'car-problems': 'Car Problems',
  'fault-codes': 'Fault Codes',
  'vehicle-guide': 'Vehicle Guide',
  'oil-guide': 'Oil & Fluids',
  'maintenance': 'Maintenance',
  'diagnosis': 'OBD-II & Diagnostics',
  'local': 'Local Guide',
  'buying-guide': 'Buying Guide',
}

export function getArticleBySlug(slug) {
  return articles.find((a) => a.slug === slug)
}

export function getArticlesByCategory(category) {
  return articles.filter((a) => a.category === category)
}
